Add --prefix-lines-with option
antmicro/tuttest pull request #11
Opened 2020-09-18 09:28 UTC by kamilrakoczy

This PR adds ``--prefix-lines-with`` option.

Signed-off-by: Kamil Rakoczy <krakoczy@antmicro.com>

2020-09-23 21:35 UTC, mgielda commented
@kgugala this will close #10 - could we get it merged?

2020-09-24 08:11 UTC, acomodi requested changes
Comments in

2020-09-24 08:11 UTC, acomodi commented on bin/tuttest
> +            prefixed_code.append(prefixed_snipped)
Snipped -> snippet

2020-09-24 08:11 UTC, acomodi commented on README.md
> +  * `<prefix>` is a command, that snippet should be prefixed with.
```suggestion
  * `<prefix>` is a command that is added to the snippet as a prefix.
```

2020-09-24 09:15 UTC, kamilrakoczy commented on bin/tuttest
> +            prefixed_code.append(prefixed_snipped)
fixed

2020-09-24 09:16 UTC, kamilrakoczy commented on README.md
> +  * `<prefix>` is a command, that snippet should be prefixed with.
fixed

2020-09-24 09:46 UTC, acomodi commented
@kamilrakoczy I am thinking that it is worth adding a test for the `--prefix-lines-with` feature

2020-09-25 07:59 UTC, acomodi approved these changes
LGTM

2020-09-25 07:59 UTC, merged